name: Waka Readme

on:
  schedule:
    - cron: '00 17 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: False
          SHOW_OS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
